# numpy library

Numpy es una librería para python de algebra lineal. Esta librería suele ser la base sobre la que se construye el resto de librerías para el análisis de datos.

## Arrays 

La principal estructura de datos que usaremos con numpy son los arrays. Éstas pueden tener dos implementaciones:

- vectores -> array de 1 dimensión
- matrices -> array de 2 dimensiones

PAra crear un array de numpy partimos del objeto `list`  de python. 

### Cómo creamos arrays (1D 2D) en numpy

tenemos varias maneras de hacer esto:

1. A partir de un  objeto list de python

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np

- 1D array

In [ ]:
np_array = np.array(['a','b','c'])
np_array

array(['a', 'b', 'c'], dtype='<U1')

* 2D array o Matrices

In [ ]:
np_matrix = np.array([
    ['a','b','c'],
    ['d','e','f']
    ])

np_matrix

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

Cuando construimos un array 2D internamente esos valores crean un bloque en memoria con los valores consecutivos

In [72]:
np_matrix = np.array([
    [5,10,15,20],
    [25,30,35,40],
    [45,50,55,60]
    ])

np_matrix

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

como es un array BIDIMENSIONAL numpy crea dos ejes (`axis 0` y `axis 1`)

![not found](../../img/10.png)

![not found](../../img/11.png)

por eso cuando queremos acceder usando los dobles corchetes lo q hacemos es indicar primero la posición en el axis 0 y después del eje 1

In [73]:
np_matrix[1][0]

25

In [74]:
np_matrix[1,0]

25

Cuando utilizamos la función `sum()`  de los arrays de numpy al pasarle el argumento `axis` lo tenemos que ver sobre qué eje colapsará la matriz, si ponemos axis=0 colapsarán las filas unas encima de otras por lo q los valores de cada columna se sumarán.

In [86]:
np_matrix

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [87]:
print(f' colapsamos a lo largo del axis0 : {np.sum(np_matrix,axis=0)}')
print(f' colapsamos a lo largo del axis0 : {np.sum(np_matrix,axis=1)}')

 colapsamos a lo largo del axis0 : [ 75  90 105 120]
 colapsamos a lo largo del axis0 : [ 50 130 210]


In [89]:
np_matrix[ [0,1,2], [0,1,2]] = 0
np_matrix


array([[ 0, 10, 15, 20],
       [25,  0, 35, 40],
       [45, 50,  0, 60]])

* 3D array

In [92]:
np_3D = np.array(
[
    [
        [10,20],
        [30,40],
        [50,60]
        
    ],
    [
        [11,12],
        [13,14],
        [15,16]
    ]
]
)

np_3D

array([[[10, 20],
        [30, 40],
        [50, 60]],

       [[11, 12],
        [13, 14],
        [15, 16]]])

Para imaginarnos una matriz de `3 dimensiones` podemos utilizar la imagen de una row de matrices 2D  

![not found](../../img/12.png)

In [91]:
np_3D[0,:,1]= 5

np_3D

array([[[ 1,  5],
        [ 3,  5],
        [ 5,  5]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

[0, : , 1 ]   
            => (0) cogemos la primera matriz  
            => (:) cogemos todas las filas  
            => (1) cogemos la columna con índice 1  


![not found](../../img/14.png)

si tuviera 4D sería matriz de filas de matrices

![not found](../../img/13.png)

---
2. Generar array de una secuencia con `arange(strat,stop,step)`

arange == array range, implementación del range de python pero devolviendo un objeto array

start -> inclusive   
stop  -> exclusive

Por defecto starts at 0 y el step es 1

In [20]:
# arange(start,end,step)
my_numpy_array = np.arange(10)

my_numpy_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_numpy_array_pares = np.arange(0,10,2)

my_numpy_array_pares

array([0, 2, 4, 6, 8])

---
3. `zeros()` method de numpy

Nos generará un array de 0s. Esta función solo tiene un atributo obligatorio y es el `shape` del array resultante que lo pasamos como una tupla.

In [21]:
my_numpy_array_all_zeros = np.zeros(10)
my_numpy_array_all_zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
# le podemos pasar una tupla para generar una matriz de zeros con tantas filas y columnas indique la tupla
my_numpy_matrix_all_zeros = np.zeros( (10,10))
my_numpy_matrix_all_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Si nos fijamos devuelve 0 en formato float (por defecto ) si necesitamos enteros podemos especificarlo con `dtype="int64" `

In [53]:
np.zeros( shape=(3,3), dtype='int64')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

---
4. `ones()` method de numpy

In [26]:
# tenemos el mismo método pero para generar 1s

my_numpy_matrix_all_ones = np.ones( (10,10))
my_numpy_matrix_all_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

---
2. `full()` Generar array que contenga un mismo valor

muy similar a la anterior pero pasamos el valor que contendrá el array

In [ ]:
np.full( shape=(3,5), fill_value="cat" )

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

---
5. `linspace(start,stop,num)` method de numpy

Con este método obtenemos un **VECTOR** con tantos floats como le indiquemos dentro de un rango especificado, es muy parecido a arange pero este método no acepta el argumento step en su lugar lo calcula por nosotros para devolvernos una sucesión de tantos números como le indiquemos separados entre sí por la misma distancia.

In [61]:
# linspace(start,stop, items)
my_numpy_array_with_floats = np.linspace(0,50,10)
my_numpy_array_with_floats

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [19]:
np.linspace(2,5,15)

array([2.        , 2.21428571, 2.42857143, 2.64285714, 2.85714286,
       3.07142857, 3.28571429, 3.5       , 3.71428571, 3.92857143,
       4.14285714, 4.35714286, 4.57142857, 4.78571429, 5.        ])

In [20]:
step = (5-2) / 14  # Divide the range into 14 intervals
[2 + step*interval for interval in range(15)]


[2.0,
 2.2142857142857144,
 2.4285714285714284,
 2.642857142857143,
 2.857142857142857,
 3.071428571428571,
 3.2857142857142856,
 3.5,
 3.7142857142857144,
 3.9285714285714284,
 4.142857142857142,
 4.357142857142858,
 4.571428571428571,
 4.785714285714286,
 5.0]

esta función puede acceptar como start y stop un array, estos arrays deben tener siempre la misma longitud, de tal forma que devolverá una matriz en la q cada columna será la distancia entre el item correspondiente del array de inicio con el item del array de stop 

en esta función existe un tercer argumentos `axis` que nos permite orientar esta matriz en el eje 0 o 1 (por defecto es axis=0) 

In [28]:
np.linspace(start=[0,5,10],stop=[10,15,20], num= 5)

array([[ 0. ,  5. , 10. ],
       [ 2.5,  7.5, 12.5],
       [ 5. , 10. , 15. ],
       [ 7.5, 12.5, 17.5],
       [10. , 15. , 20. ]])

In [29]:
np.linspace(start=[0,5,10],stop=[10,15,20], num= 5, axis= 1)

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 5. ,  7.5, 10. , 12.5, 15. ],
       [10. , 12.5, 15. , 17.5, 20. ]])

---
6. `eye()` method de numpy

Con este método obtenemos una **MATRIZ** cuadrada (mismo número de filas q de columnas) con una diagonal de 1s y el resto 0s. La longitud de esa diagonal dependerá del argumento que le pasemos.

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---
5. `random` librería de numpy
   

Con este método obtenemos un **VECTOR** de números aleatorios. Hay muchos métodos asociados a random

1. `random.rand()`

Crea un array con números aleatorios siguiendo una distribución uniforme continua entre 0 y 1. Esto son valores que son igualmente probables.

In [35]:
np.random.rand(5)

array([0.6889802 , 0.1076583 , 0.01718556, 0.38687735, 0.8048123 ])

 Si le pasamos dos argumentos obtendremos una matriz de tantas filas y columnas como indiquemos.

In [36]:
np.random.rand(5,5)

array([[0.25623533, 0.6856197 , 0.27062885, 0.91208668, 0.26693637],
       [0.53304596, 0.30156866, 0.20066465, 0.18936629, 0.93109745],
       [0.51361192, 0.00563403, 0.94819684, 0.15939958, 0.45942   ],
       [0.67201294, 0.75736582, 0.54632939, 0.86049626, 0.67303527],
       [0.21972332, 0.88573755, 0.35405025, 0.18458412, 0.85303295]])

2. `random.randn()`

En este caso nos devolverá un vector o una matriz de números aleatorios entre 0 y 1 pero siguiendo una distribución normal o de GAUSSIAN

In [37]:
np.random.randn(5)

array([ 0.23038071, -1.56075398,  0.71175868, -1.9609358 ,  1.89424902])

In [40]:
np.random.randn(5,5)

array([[ 0.25483774, -0.38069919, -0.14975704, -0.29213181, -0.0577875 ],
       [ 0.26414598,  1.44585143, -0.2644027 ,  0.37485831,  2.95136954],
       [-0.81439929,  0.92320972, -0.31951123, -0.47036418, -0.27572224],
       [ 0.38879302,  0.01038197, -0.36875331,  1.70112662, -1.25496152],
       [-1.44063941, -1.2862593 , -0.15482413, -2.73514673, -0.36912146]])

3. `random.randint(low,high,size)`

Nos devuelve un/varios **INTEGER** aleatorio/s contenido en un intervalo donde el límite inferior está incluido y el mayor excluido. Podemos pasar un tercer argumento q es el número de integers devueltos.

In [43]:
# [start,end,items)
# [  -> means inclusive interval
# ( -> means exclusive interval

np.random.randint(1,100,10)

array([29, 45, 65,  2, 39, 47, 45, 11, 14,  8])

In [49]:
np.random.randint(low=10,high=20,size=(2,3))

array([[10, 11, 14],
       [10, 12, 17]])

### Usando NaN para representa valores missings o valores no válidos

El valor NaN es un tipo de dato especial en numpy ya que está implementado como un constante númerica tipo float pero es tratado por np de manera diferente, hasta el punto q si hacemos np.nan == np.nan es False.

Como nan es un tipo de float solo puede existir en matrices del tipo float.



In [49]:
np.nan == np.nan

False

Así para evaluar si en nuestros datos tenemos valores `nan` debemos usar la función `np.isnan`

In [50]:
bot = np.ones(shape=(3,4))
bot[ [0,2], [1,2]] = np.nan
bot

array([[ 1., nan,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1., nan,  1.]])

In [55]:
np.isnan(bot)



array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

### Representar valores infinitos en numpy

Como el caso de los valores nan los valores infinito y infinito negativo son representados como constantes floats que son tratados de manera especial por numpy.





In [56]:
np.array([np.inf, np.NINF])

array([ inf, -inf])

## Métodos de los arrays

1. `reshape()`

Nos permite modificar un array d 1D y convertirlo en una matriz de tantas filas y columnas como le pasemos pero siempre respetando la longitud del array original, Es decir si partpo de un array de 25 posiciones y hago un reshape tiene q tener un número de filas y columnas compatible con 25 posiciones. Reshape devuelve una copia del array original **NO** modifica el array original!!

teniendo en cuenta q rechape no modifica el original si quisieramos modificarlo en luegar de reasignar usando reshape

In [81]:
foo = np.arange(8)

foo = foo.reshape(2,4)
foo

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

podemos usar el atributo `shape` de los arrays y así modificamos directamente

In [83]:
foo = np.arange(8)

foo.shape = (2,4)
foo

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
numpy_arr_1      = np.arange(30)
numpy_arr_random = np.random.randint(0,50,10)

In [59]:
# reshape(rows, columns) 
numpy_arr_1.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
foo = np.arange(start=1, stop=9)
foo

array([1, 2, 3, 4, 5, 6, 7, 8])

Podemos convertir foo en una matriz de 2 X 4 usando el método reshape, podemos usar dos interfaces, directamente sobre el array 1D o bien usar el método sobre numpy. Son dos interfaces pero con la misma implementación.

In [54]:
foo.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.reshape(a = foo, newshape= (2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Este reshape puede hacerse con diferente orden: C == Row major order (por defecto) o F (column order major)

lo que hace el orden C es q desde nuestro array 1D [1, 2, 3, 4, 5, 6, 7, 8] lo transforma a 2D => 4 (filas) x 2(columnas) empieza a tomar los números hasta comletar una primera fila (como el 2D resultante tiene dos columnas) toma los primeros 2 número y genera una fila con ellos para obtener dos columnas

![not found](../../img/27.png)

In [86]:
foo.reshape( (4,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Si obtamos por el orden F lo q rellena primero son las columnas, si tenemos el array [1, 2, 3, 4, 5, 6, 7, 8]  los 4 primeros números forman las columnas en posición 0 y los últimos 4 números la columna 1

In [65]:
foo.reshape( (4,2), order='F')

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Ahora bien qué sucede si en lugar de partir de un array 1D partimos ya de una matriz, por ejemplo:

In [71]:
bar = foo.reshape(2,4)
bar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

En el caso de orden C no cambia xq empieza por el índice 0,0 y va comletando el nuevo array

In [72]:
bar.reshape( (4,2), order='C' )

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Pero si aplicamos el orden F genera primero las columnas y para ello va cogiendo los números de la columna con índice 0 en nuestro caso coge primero el 1 (0,0) y el 5 (1,0) como nos queda por completar sigue por la columna 1 q sería el 2 (0,1) y el 6 (1,1) y así iría completando

In [73]:
bar.reshape( (4,2), order='F' )

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

**TIP**

hay una manera para hacer un reshape fijando una de las dimensiones resultantes y dejar a numpy calcular la otra y es usando el `-1 ` 

In [78]:
bar.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

2. transponse()

Solo funciona en arrays de 2D hacia adelante. Lo q hace en convinar, en el caso de un array 2D, todos los valores de la primera columna de las ditintas filas en una fila. Mirar el ejemplo:

![not found](../../img/28.png)

In [105]:
boo = np.arange(start=1, stop=9)
boo.shape = (2,4)
boo

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
boo = boo.T
boo

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [107]:
boo.shape

(4, 2)

In [17]:
names = np.array([ 
    ['Dennis','Dee','Charlie','Mac','Frank'],
    [43,44,43,42,74],
    ['male','female','male','male','male']
    ])
names

array([['Dennis', 'Dee', 'Charlie', 'Mac', 'Frank'],
       ['43', '44', '43', '42', '74'],
       ['male', 'female', 'male', 'male', 'male']], dtype='<U21')

In [18]:
names.transpose()

array([['Dennis', '43', 'male'],
       ['Dee', '44', 'female'],
       ['Charlie', '43', 'male'],
       ['Mac', '42', 'male'],
       ['Frank', '74', 'male']], dtype='<U21')

2. `max() / min()`

Nos devuelve el max y min valor dentro de un array (tanto de integers como floats)

In [64]:
numpy_arr_random.max()

44

In [65]:
numpy_arr_random.min()

1

3. `argmax() / argmin()`

Nos devuelve el ínidice dónde se encuentra el valor máximo y mínimo

In [68]:
numpy_arr_random.argmax()

2

In [67]:
numpy_arr_random.argmin()

0

3. `shape` atributo

nos devuelve una tupla con la estructura del array. Si es:
- 1D nos devuelve el número de items (25,)
- 2D matriz nos devolvería (5,5) == (filas, columnas)

In [69]:
numpy_arr_random.shape

(10,)

In [70]:
my_numpy_matrix_all_ones.shape

(10, 10)

4. `dtype` atributo

Nos devuelve el tipo de datos que contiene el array siempre y cuando ese array contenga un único tipo de dato.

In [58]:
my = [1,2,3]
my_numpy = np.array(my)

my_numpy.dtype

dtype('int64')

5. `ndim` nos devuelve la dimensión del array

In [60]:
my_numpy.ndim

1

6. `len` vs `size`

Si miramos la longitud del array 2D nos dará el número de elementos contenidos en el primer array, es decir 2, si hacemos size de un 2D nos dará el total de elementos contenidos en el array

In [62]:
my_2d_arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

print(f'len() del 2D => {len(my_2d_arr)}')
print(f'size del 2D => {my_2d_arr.size}')

len() del 2D => 2
size del 2D => 10


## Numpy indexing and selection

Para acceder a los elementos de un array de numpy es igual q las listas de python

In [64]:
foo = np.array([10,20,30,40,50])

foo[0]

10

También podemos pasar un array con los índices q necesitamos, incluso podemos repetir índices 

In [ ]:


foo[ [0,0,1] ]

array([10, 10, 20])

siguiendo esta sintaxis tb podemos modificar varios elementos a la vez, pero la list q le pasemos tiene q tener la misma longitud q el número de elementos a cambiar

In [70]:
foo[ [0,3,4] ]  = [99, 88 ,77]

foo

array([99, 20, 30, 88, 77])

Podemos modificar varios elementos a un mismo valor

In [71]:
foo[ [0,3,4] ]  = 66

foo

array([66, 20, 30, 66, 66])

#### 1. Slicing 

A diferencia que en python cuando hacemos un slicing en numpy no hacemos una copia del array original y ambos son independientes, sino que en numpy un slincing es más bien una **VISTA** del array original. NUMPY FUNCIONA ASÍ PARA EVITAR PROBLEMAS DE MEMORIA EN ARRAYS MUY GRANDES. 

El problea de esto es que si cambiamos el subarray resultante de splicing tb modificamos el array original

In [69]:
foo2 = np.array([10,20,30,40,50])

foo3 = foo2[:3]

foo3[0] = 100

print(f'array original :        {foo2}')
print(f'subarray con splicing : {foo3}')

array original :        [100  20  30  40  50]
subarray con splicing : [100  20  30]


Este es el comportamiento por defecto pero si realemte queremos hacer una copia con el slincing tenemos que primero hacer una copia con el método `copy()`

In [63]:
arr = np.arange(11)

arr2 = arr.copy()[:3]


arr2[0] = 100
print(arr2.dtype )
print(arr,type(arr))
print(arr2,type(arr2))


int64
[ 0  1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
[100   1   2] <class 'numpy.ndarray'>


In [95]:
print(f'[0]   -> {arr[0]}')    # getting first element
print(f'[1:5] -> {arr[1:5]}')  # elementos entre posición 1 (incluido) y posición 5 (NO incluido)
print(f'[0:5] -> {arr[0:5]}')
print(f'[:5]  -> {arr[:5]}')   # elementos entre la primera posición (incluido) hasta la posición 5 (NO incluido)
print(f'[5:]  -> {arr[5:]}')   # elementos desde posición  (NO incluido) hasta el final

[0]   -> 0
[1:5] -> [1 2 3 4]
[0:5] -> [0 1 2 3 4]
[:5]  -> [0 1 2 3 4]
[5:]  -> [ 5  6  7  8  9 10]


#### 2. Broadcast

El broadcasting en numpy es cuando aplicamos un valor a todos los elementos de un array o bien cuando operamos entre arrays de la misma longitud cada elementos de un array opera con el elemento correspondiente del otroa array

In [34]:
np.array([1,2,3]) + 10 

array([11, 12, 13])

In [35]:
np.array([1,2,3]) + np.array([10,20,30])

array([11, 22, 33])

![not found](../../img/17.png)

Si intentamos sumar una matriz (2D-array) con 1D-array, siempre y cuando tengan el mismo número de " columnas " numpy no da error 

![not found](../../img/18.png)

si `boo ` tuviera una longitud mayor o menor no podríamos hacer broadcast. Nos daría error

![not found](../../img/19.png)

* Reglas del brodcasting

Si tenemos un array A y un array B...

1. Se comprueba que cada dimensión de cada array son compatibles
2. Dos dimensiones son compatibles si tienen la misma longitud o una de ellas es 1

Para comparar dimensiones empezamos por el final!!

Si tenemos los arrays A y B

![not found](../../img/20.png)


como la útima dimensión de B es 1 y la primera dimensión es 3 y 2 son arrays compatibles para el broadcast

el siguiente ejemplo no permite el broadcast pq la primera dimensión no es compatible.

![not found](../../img/21.png)

Como último ejemplo tenemos lo siguiente:

![not found](../../img/22.png)

en este caso podemos ir adaptando las dimensiones de cada array para q puedan cuadrar y así poder operar. En array B falta la primera dimensión en su defecto se adapta a la de A

![not found](../../img/23.png)

Entender esto es útil porque por ejemplo si yo tengo dos arrays A y B y quiero restar cada elemento de B a cada elemento de A

![not found](../../img/24.png)


Esto nos dara error pero si somos capaces de modificar el `shape` del array podremos obtener lo q buscamos aprovechando el broadcasting.

Transformamos los array 1D en matrices 

![not found](../../img/25.png)


teniendo esto podemos aplicar broadcasting y sería como realizar la siguiente oiperación

![not found](../../img/26.png)

Para combertir el 1D-array A  en una matriz (4,1) hacemos `A[:,np.newaxis]` 

In [45]:
A=np.array([ 3, 11, 4, 5])


# (4,1)
A = A[:,np.newaxis]
A

array([[ 3],
       [11],
       [ 4],
       [ 5]])

In [51]:
B=np.array([ 5, 0, 3])


# (1,3)
B = B[np.newaxis,:]
B

array([[5, 0, 3]])

Una vez hecha esta transformación ya podemos aplicar la operación

In [49]:
A - B

array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])


Broadcast junto con slicing nos permite sustituir los elementos del sub-array x el valor facilitado. 

In [113]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr2 = arr[:5] 
arr2[:]=99

In [117]:
arr2

array([99, 99, 99, 99, 99])

In [118]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [119]:
numpy_arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

numpy_arr2 = numpy_arr1[:3]

In [120]:
numpy_arr2[:] = 99

In [121]:
# AQUÍ VEMOS COMO CAMBIA TANTO EL ARRAY ORIGINAL COMO EL DEL SPLICING
# NUMPY FUNCIONA ASÍ PARA EVITAR PROBLEMAS DE MEMORIA EN ARRAYS MUY GRANDES

numpy_arr1,numpy_arr2

(array([99, 99, 99,  4,  5,  6,  7,  8,  9, 10]), array([99, 99, 99]))

In [122]:
# SI REALMENTE QUEREMOS HACER UNA COPIA TENDREMOS QUE ESPECIFICARLO

numpy_arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

numpy_arr2 = numpy_arr1.copy()[:3]

In [124]:
numpy_arr2[:] = 99

In [125]:
numpy_arr1,numpy_arr2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([99, 99, 99]))

### indexing en una matriz (array 2D)

Tenemos dos notaciones:

- doble corchete
- un corchete con coma

In [130]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [132]:
arr_2d[0][0]

1

In [133]:
#   fila, columna
arr_2d[0,0]

1

Ahora podemos usar esta matriz booleana para realizar una acción sobre la matriz original, por ejemplo todos los items==3 convertirlos en 0

#### slicing con la notación de la coma

In [137]:
#      fila,columna
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [143]:
t = arr_2d[:2]

t[:] = 99

t

array([[99, 99, 99],
       [99, 99, 99]])

In [144]:
# SUCEDE LO MISMO Q CON EL ARRAY 1D EL SLICING EN MATRICES TB ES UNA VISTA DE LA MATRIZ ORIGINAL ASÍ 
#  SI LA MODIFICAMOS TB LO HACEMOS SOBRE LA MATRIZ ORIGINAL

arr_2d

array([[99, 99, 99],
       [99, 99, 99],
       [ 7,  8,  9]])

#### Seleccion condicional o Boolean indexing

Partiendo de nuestro array podemos creae su equivalente en booleanos, es decir evaluar cada elemento del array según una ocndición

In [148]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:

bool_arr = arr > 5

bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [150]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

* podemos hacer esto en un mismo paso

In [154]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

podemos evaluar cualquier condición

In [155]:
arr[arr % 2 == 0] # pares

array([ 0,  2,  4,  6,  8, 10])

In [156]:
arr2 = np.arange(50).reshape(5,10)

arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [157]:
arr2[2,3:8]

array([23, 24, 25, 26, 27])

otro ejemplo de boolean indexing

In [ ]:
foo = np.array([
    [3,9,7],
    [2,0,3],
    [3,3,1]
])

foo

array([[3, 9, 7],
       [2, 0, 3],
       [3, 3, 1]])

In [ ]:
mask = foo == 3
mask

array([[ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

Ahora podemos usar esta matriz booleana para realizar una acción sobre la matriz original, por ejemplo todos los items==3 convertirlos en 0

In [ ]:
foo[mask]=0

foo

array([[0, 9, 7],
       [2, 0, 0],
       [0, 0, 1]])

In [36]:
names = np.array(['Dennis','Dee','Charlie','Mac','Frank'])
ages = np.array( [43,44,43,42,74])
genders = np.array( ['male','female','male','male','male'])


Quien es mayor de 44?

In [33]:
ages>=44

array([False,  True, False, False,  True])

In [32]:
names[ages>=44]

array(['Dee', 'Frank'], dtype='<U7')

hombres mayors de 42

In [37]:
names[ (ages>42) & (genders=='male')]

array(['Dennis', 'Charlie', 'Frank'], dtype='<U7')

Quien no es hombre o is menor de 43

In [38]:
names[ (ages<43) | ~(genders=='male')]

array(['Dee', 'Mac'], dtype='<U7')

## Operaciones matemáticas con arrays

In [9]:
arr3 = np.arange(11)
arr4 = np.arange(11)

foo = np.array([ [4,3], [1,0]  ])
bar = np.array([ [1,2], [3,4]  ])

Si sumo dos matrices, sucede lo siguiente:

![not found](../../img/15.png)

y esto para cada operación, siempre se sumará el valor de la posición [0,0] de la matriz A con el valor de la posición [0,0] de la matriz B y así con todas las posiciones.

In [15]:
foo


array([[4, 3],
       [1, 0]])

In [16]:
bar

array([[1, 2],
       [3, 4]])

In [12]:
foo + bar

array([[5, 5],
       [4, 4]])

In [18]:
foo - bar

array([[ 3,  1],
       [-2, -4]])

In [19]:
foo * bar

array([[4, 6],
       [3, 0]])

In [20]:
foo / bar

array([[4.        , 1.5       ],
       [0.33333333, 0.        ]])

Cuando queremos sacar el `producto matricial` de dos matrices usamos el operador `@` de numpy. Para poder multiplicar dos matrices A y B el número de columnas de A debe coincide con el número de filas de B.

![not found](../../img/16.png)

In [22]:
foo = np.array([ [2,0], [1,9]  ])
bar = np.array([ [3,9], [4,7]  ])

In [23]:
foo @ bar

array([[ 6, 18],
       [39, 72]])

Si sumo vecores (1D-arrays) ES NECESARIO QUE TENGAN LA MISMA LONGITUD

In [24]:
arr5 =arr3 + arr4
arr5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [188]:
arr5 + 100

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120])

In [187]:
arr5*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [185]:
arr5 =arr3 - arr4
arr5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# ESTO ES LO Q PASA CON LOS ARRAYS EN PYTHON, NO SE SUMAN SE CONCATENAN X LO Q PUEDEN TENER LONGITUDES DIFERENTES

l = [1,2,3]
l2= [1,2]

l + l2

[1, 2, 3, 1, 2]

In [193]:
arr5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [192]:
arr5 ** 2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [190]:
# UN COMPORTAMINETO DISTINTO DE LOS ARRAYS DE NUMPY ES Q SI SE ENCUENTRAN CON UNA OPERACIÓN QUE 
# NO TIENE SOLUCIÓN COMO DIVISIÓN ENTRE 0 NO PARA LA EJECUCIÓN
print(arr5)
arr5 / arr5

[ 0  2  4  6  8 10 12 14 16 18 20]


/tmp/ipykernel_7690/4288252157.py:4: RuntimeWarning: invalid value encountered in divide
  arr5 / arr5


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [191]:
1 / arr5

/tmp/ipykernel_7690/1138687670.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr5


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       , 0.08333333, 0.07142857, 0.0625    , 0.05555556,
       0.05      ])

In [194]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [198]:
# CALCLA LA EXPONENCIAL DE CADA UNO DE LOS NÚMEROS DEL ARRAY, ESTO ES e elevado a cada número del array
np.exp(arr3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [200]:
np.max(arr3)

10

In [202]:
np.min(arr3)

0

In [203]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [204]:
np.log(arr3)

/tmp/ipykernel_7690/2430430252.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Numpy curso de youtube

[source](https://www.youtube.com/watch?v=eClQWW_gbFk)  
[funciones-numpy](https://www.javatpoint.com/numpy-tutorial)

## Arrays

Los arrays n-dimensionales son la principal estructura de datos en numpy. Numpy surge ante la necesidad de gestionar de una manera más eficiente las listas de python, y poder realizar cálculos estadísticos sobre los valores que contiene.
Lo mñas eficiente para trabajar con los arrays de numpy es q contengan el mismo tipo de dato, aunq se puedan almacenar distintos tipos a la vez pero no es recomendable.

Ventajas de numpy:

- muchos más rápido 
- sintaxis sencilla

Uno de los motivos por los q arrays en numpy son más rápidos es pq cada elemento contenido en el array ocupa una misma longitud. Por ejemplo si guardamos integers estos ocupan 32  bits, por lo q si queremos el 3 elementos solo tiene q contar 32 + 32 +32 para llegar al elemento lo q lo hace muy rápido. Y así con todos los tipos de datos, guardemos lo q guardemos. 

![not found](../../img/7.png)

Ahora bien las `lists` de python funcionan diferente, éstas guardan direcciones de memoria. Es como solucionan el problema de los strings.

Ahora bien que sucede con los strings? pues que los strings tienen longitudes diferentes por lo q ocupan un espacio diferente en memoria o incluso si sustituimos un string corto por otro de mayor longitud por lo q no se puede aplicar lo anterior.

![not found](../../img/8.png)

la solución fue almacenar en LA LISTA la dirección en momoria de esos objetos, esa dirección se puede representar como un int de 32 bits. ESTO SUCEDE EN LA IMPLEMENTACIÓN DE LAS `LIST` DE PYTHON. 

En `numpy` lo q hace es fijar un tamaño para cada elemento del array en función del string de mayor tamaño.

#### implementacion listas python

![not found](../../img/9.png)

In [9]:
# puedo crear un array de integers y strings, para respetar q todos los elemenmtos sean del mismo tipo numpy hace un cast de los int a str

my_int_str_arr = np.array([1,'hello',2])

PERO automáticamente nos fija un tamaño para todos los elementos en `<U21` es decir todos los elementos tendrán una longitud inferior a 21 carcateres. Así si sustituyo el `1`  por un string solo guardará los primeros 21 carcateres

In [11]:
print(my_int_str_arr[0])
my_int_str_arr[0] = 'esto es un string muy muy muy pero que muy largo'

print(my_int_str_arr[0])

1
esto es un string muy


vemos como el string se trunca pq numpy fija esa posición a 21 cracteres.

Si creamos directamente una array de strings cogerá el string de mayor tamaño y fijara la longitud máxima de los elementos de ese array a ese valor máximo.

In [14]:
my_str_arr = np.array(['hi','there'])

my_str_arr.dtype


dtype('<U5')

En el ejemplo vemos que al array `my_str_arr` le fija un tamaño max por elemento de 5, si intento modificar el primer elemento lo truncará


In [16]:
my_str_arr[0] = 'goodMorning'

my_str_arr

array(['goodM', 'there'], dtype='<U5')

In [76]:
# puedo crear un array de integers y strings, para respetar q todos los elemenmtos sean del mismo tipo numpy hace un cast de los int a str

np.array([1,'hello',2])

array(['1', 'hello', '2'], dtype='<U21')

Algo parecido sucede cuando tenemos `ints`  and `floats`, numpy los castea todos a floats

In [17]:
np.array([
    [1,2,3],
    [5.5,5.6,5.7]
])

array([[1. , 2. , 3. ],
       [5.5, 5.6, 5.7]])

Ahora el principio de los arrays dice q tienen q ser cuadradas, mismo número de filas q de columnas, si no respetamos este principio numply aplica un `dtype=object` lo q se asemeja a la solución planteada en las implementacion listas python

In [19]:
np.array([
    [1,2,3],
    [5]
])

/tmp/ipykernel_36791/1059078976.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([


array([list([1, 2, 3]), list([5])], dtype=object)

### Generar arrays en numpy

1. Generar array a partir de una `list` de python

- 1D array

In [22]:
np_array = np.array(['a','b','c'])
np_array

array(['a', 'b', 'c'], dtype='<U1')

* 2D array o Matrices

In [23]:
np_matrix = np.array([
    ['a','b','c'],
    ['d','e','f']
    ])

np_matrix

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

* 3D array

In [27]:
np_3D = np.array(
[
    [
        ['a','b','c']
        
    ],
    [
        ['d','e','f']
    ]
]
)

np_3D

array([[['a', 'b', 'c']],

       [['d', 'e', 'f']]], dtype='<U1')

# Ejercicios

1. Anotamos nuestro peso cada día durante 5 semanas, dado esos datos contruir un array con la media de los pesos por semana

In [25]:
dailywts = 185 - np.arange(5*7)/5
dailywts

array([185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8, 183.6, 183.4,
       183.2, 183. , 182.8, 182.6, 182.4, 182.2, 182. , 181.8, 181.6,
       181.4, 181.2, 181. , 180.8, 180.6, 180.4, 180.2, 180. , 179.8,
       179.6, 179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2])

In [33]:
dailywts.resize(5,7)
dailywts


array([[185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8],
       [183.6, 183.4, 183.2, 183. , 182.8, 182.6, 182.4],
       [182.2, 182. , 181.8, 181.6, 181.4, 181.2, 181. ],
       [180.8, 180.6, 180.4, 180.2, 180. , 179.8, 179.6],
       [179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2]])

In [35]:
dailywts[:,[-2,-1]].sum(axis=1)/2


array([183.9, 182.5, 181.1, 179.7, 178.3])

Otra solución podría ser, buscar la posición de todos los sábados ([5::7] esto es start(5):stop(by default -1):step(7))  y luego hacemos lo mismo con los domingos ([6::7] ) finalmente sumamos los vectores y dividimos entre 2

In [43]:
dailywts2 = 185 - np.arange(5*7)/5
dailywts2

sabados =  dailywts2[5::7]
domingos = dailywts2[6::7]

pesos_medios = (sabados + domingos)/2

pesos_medios

array([183.9, 182.5, 181.1, 179.7, 178.3])

2. Tenemos un matriz gold que representa un terreno dividido en cuadrícula de 7x7 y en cada posición se encuentra una cantidad de oro. Luego tenemos la matriz loc con localizaciones (fila,columna).

Calcular cuanto oro hay por localización.

In [4]:
np.random.seed(5555) # es como un punto inicial paa el algoritmo q genera el número aleatorio, si lo fjamos el valor de los números aleatorios siempre será el mismo
gold = np.random.randint(low=0,high=10,size=(7,7))
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3],

])

In [15]:
total_gold = 0

for loc in locs:
    row,col = loc
    total_gold+=gold[row,col]

total_gold

20

Otra solución  
Funciona pq podemos pasar una array con todas las filas deseadas y otro array con su correspondiente columna

In [19]:
gold[locs[:,0],locs[:,1]].sum()

20

1. Decidimos poner unos letreros que anuncien nuestro restaurante que está en el kilometro 30. Exactamente podenomos 3 letreros del km 17 al 28 y otros 3 letreros del km 32 al 36. En total del km 17 al 36 nuestros letreros muestran las letras A B C C B A. Cada letrero se situa a una misma distancia unos de otros. 


Qué distancia hay desde los letreros C hasta nuestro restaurante?.

In [24]:
first_c = abs(30 - np.linspace(17,28,3)[-1])
print(f' distancia del primer C al resta {first_c} km')

 distancia del primer C al resta 2.0 km


In [25]:

second_c = abs(30 - np.linspace(32,36,3)[0])
print(f' distancia del primer C al resta {second_c} km')

 distancia del primer C al resta 2.0 km


Otra manera de hacerlo sería:

In [33]:
distancia = np.abs(np.linspace(start=[17,32], stop=[28,36], num= 3, axis = 1)-30)
distancia[[0,1],[-1,0]]

array([2., 2.])

In [1]:
from datetime import datetime

 

datetime = datetime(2019, 11, 27, 11, 27, 22)

print(datetime.strftime('%Y/%m/%d %H:%M:%S'))

2019/11/27 11:27:22


In [4]:
class Count:

   def __init__(self, count=0):

      self.__count=count

 

a=Count(2)

b=Count(2)

print(id(a)==id(b), end = "")

 

c= "hellooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo"

d= "hellooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo"

print(id(c)==id(d))

100 400


In [14]:
class P:

   def __init__(self):

      self.__x=100

      self.y=200

   def print(self):

      print(self.__x, self.y) 

class C(P):

   def __init__(self):

      super().__init__()

      self.__x=300

      self.y=400 

d = C()

d.print()

100 400


In [13]:
z = 2

y = 1

#x = y < z or z > y and y > z or z < y
x = True or (True and False or False)

x

False

In [20]:
x = 'mio'

y = x

print(id(x))
print(id(y))

140404415172912
140404415172912


esteban.vazquez@teslatechnologies.com